---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Olegase.
--- DateTime: 02.05.2019 0:35
---

-- Функции для реакций на действия в битве

function handleUnexpectedConfirm()
    debugStatus("Handle unexpected confirm");
    if (confirmReg2:exists(confirm2, 0.5)) then
        highlight(1, _, confirmReg2);
        click(confirmReg2:getLastMatch());
        return true;
    end
    return false;
end

function updateCurrentShipLocation()
    setScanIntervalPro(0);
    local ship = exists(currentShip, 0.5);
    setScanIntervalPro(standardTimeInterval);
    if ship ~= nil then
        currentShipReg = Region(ship:getX(), ship:getY(), 180, 80);
        return true;
    end
    return false;
end

function handleAmbush(enemy)
    attemptsToReachEnemy = 5;
    while (not battleButtonReg:exists(battleButton, 2)) do
        click(enemy);
        checkAmbush();
        if (pauseButtonReg:exists(pauseButton, 1.5)) then
            highlight(1, _, pauseButtonReg);
            return;
        end
        if (attemptsToReachEnemy == 0) then
            print("Can't reach this enemy:");
            print(enemy);
            enemy:highlight();
            standardArea:save("Bug"..time:check()..".png");
            wait(5);
            enemy:highlightOff();
            print("You can find screenshot with problem place in "..scriptPath().."image/Bug*.png");
            return;
        end
        attemptsToReachEnemy = attemptsToReachEnemy - 1;
        debugStatus("Search battle button: "..attemptsToReachEnemy);
    end
    highlight(1, _, battleButtonReg);
    wait(1);
end

function handleDockIsFull()
    debugStatus("Checking dock if full");
    if (dockIsFullReg:exists(dockIsFull, 1)) then
        highlight(1, _, dockIsFullReg);
        usePreviousSnap(false);
        click(sortLoc);
        missionModeReg:wait(dock2);
        click(levelButtonReg);
        wait(0.5);
        click(rarityAllLoc);
        commonButtonReg:waitClick(commonButton);
        confirmReg4:waitClick(confirm3);
        wait(0.5);
        for _, loc in ipairs(pickAllLoc) do
            click(loc);
        end
        click(retireConfirmLoc1);
        wait(0.5);
        click(retireConfirmLoc2);
        wait(0.1);
        click(retireConfirmLoc2);
        wait(0.1);
        click(retireConfirmLoc2);
        wait(0.1);
        click(retireDisassembleLoc);
        wait(0.1);
        click(retireConfirmLoc2);
        wait(0.1);
        backReg:click(back);
        wait(1);
        return true;
    end
    return false;
end

function handleFindPathToItem(location)
    updateCurrentShipLocation();
    if (currentShipReg == nil) then
        return;
    end
    local counter = 5;
    while (math.abs(currentShipReg:getX() - location:getX()) > 50
            or math.abs(currentShipReg:getY() - location:getY() + 170) > 50) do
        debugStatus("Try to pick up item: "..counter);
        click(location);
        if (counter == 0) then
            return;
        end
        if (checkAmbush() or battleButtonReg:exists(battleButton, 0.5)) then
            fight();
            wait(1);
        end
        updateCurrentShipLocation();
        counter = counter - 1;
    end
end