---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Olegase.
--- DateTime: 06.05.2019 16:42
---

-- Цвета

lvColor = {246, 215, 70, 3, 17, 20};
lv2Color = {235, 200, 70, 4, 2, 30};
enemy_l3Color = {189, 48, 0, 8, 4, 20};
enemy_m2Color = {222, 160, 0, 4, 8, 20};
enemy_s2Color = {206, 180, 40, 5, 7, 40};
enemyRankColorAll = {enemy_l3Color, enemy_m2Color, enemy_s2Color};
retreatColorAll = {{251, 251, 244, 9, 0, 70}, _};
bossColor = {251, 76, 81, 4, 9, 20};
bossColorAll = {bossColor};