---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Olegase.
--- DateTime: 03.05.2019 19:01
---

-- Ежедневные задания

function settingsDaily()
    dialogInit();
    addCheckBox("tacticalTrainingCheck", "Tactical Training", true);
    newRow();
    addRadioGroup("tacticalTrainingRadioButton", 1);
    addRadioButton("Aviation", 1);
    addRadioButton("Shelling", 2);
    addRadioButton("Torpedo", 3);
    newRow();
    addTextView("-- Difficult of other daily");
    newRow();
    addRadioGroup("Difficult", 1);
    addRadioButton("Hard", 1);
    addRadioButton("Medium", 2);
    addRadioButton("Easy", 3);
    newRow();
    addTextView("-- Select fleet for daily");
    newRow();
    addRadioGroup("fleetDailyNumber", 1);
    addRadioButton("First", 1);
    addRadioButton("Second", 2);
    addRadioButton("Third", 3);
    addRadioButton("Fourth", 4);
    newRow();
    dialogShow("Daily");
    dailyRadioButtons = {tacticalTrainingRadioButton, Difficult, Difficult, Difficult};
end

function dailyMission()
    if (not (tacticalTrainingCheck or escortCargoCheck or maritimeAttackCheck or urgentOpsCheck)) then
        return;
    end
    local dailyMissionTime = Timer();
    if (not missionModeReg:exists(daily2, 1)) then
        goHome();
        wait(1);
        goMission();
        wait(1);
        dailyReg1:exists(daily1);
        highlight(1, _, dailyReg1);
        click(dailyReg1:getLastMatch());
        wait(1);
    end
    debugStatus("Daily mission");
    local today = os.date("%A", os.time(os.date("!*t")) - 25200);
    escortCargoCheck = (today == "Monday" or today == "Thursday" or today == "Sunday");
    maritimeAttackCheck = (today == "Tuesday" or today == "Friday" or today == "Sunday");
    urgentOpsCheck = (today == "Wednesday" or today == "Saturday" or today == "Sunday");
    groupsModeFlag = {tacticalTrainingCheck, maritimeAttackCheck, escortCargoCheck, urgentOpsCheck};
    for i, mode in ipairs(groupsModeFlag) do
        if (mode) then
            click(dailyModeReg);
            if (not messageBoxReg:exists(available, 1)) then
                local flag;
                while (not dailyAttemptsReg:exists(emptyDaily, 1)) do
                    flag = true;
                    pickDailyLevel(dailyRadioButtons[i]);
                    pickDailyFleet();
                    manualBattleCheck = (mode ~= escortCargoCheck);
                    fight();
                end
                backReg:click(back);
                wait(0.3);
                if (i == 4) then
                    break;
                end
                if (flag) then
                    for _ = 2, i do
                        click(nextDailyMode);
                        wait(0.3);
                    end
                end
            end
        end
        click(nextDailyMode);
        if (i == 3) then
            wait(0.3);
            click(nextDailyMode);
        end
    end
    print("Daily: Minutes: "..string.format("%.2f", dailyMissionTime:check() / 60));
end

function pickDailyLevel(index)
    click(dailyLevelLocAll[index]);
end

function pickDailyFleet()
    debugStatus("Pick daily fleet");
    if (not dailyFleetReg:exists(fleetAll[fleetDailyNumber], 1)) then
        local currentFleetNumber = getCurrentFleetNumber();
        while (currentFleetNumber - fleetDailyNumber > 0) do
            click(leftButtonLoc);
            currentFleetNumber = currentFleetNumber - 1;
        end
        while (currentFleetNumber - fleetDailyNumber < 0) do
            click(rightButtonLoc);
            currentFleetNumber = currentFleetNumber + 1;
        end
    end
end

function getCurrentFleetNumber()
    if (dailyFleetReg:exists(fleet1, 0.25)) then
        return 1;
    end;
    if (dailyFleetReg:exists(fleet2, 0.25)) then
        return 2;
    end;
    if (dailyFleetReg:exists(fleet3, 0.25)) then
        return 3;
    end;
    if (dailyFleetReg:exists(fleet4, 0.25)) then
        return 4;
    end;
end