---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Olegase.
--- DateTime: 03.05.2019 20:08
---

-- Точки на экране

dailyLevelLoc1 = Location(486, 213);
dailyLevelLoc2 = Location(484, 354);
dailyLevelLoc3 = Location(485, 492);
dailyLevelLocAll = {dailyLevelLoc1, dailyLevelLoc2, dailyLevelLoc3};
nextDailyMode = Location(373, 341);
rightButtonLoc = Location(775, 399);
leftButtonLoc = Location(48, 399);
sortLoc = Location(489, 492);
pick1Loc = Location(105, 187);
pick2Loc = Location(283, 187);
pick3Loc = Location(450, 187);
pick4Loc = Location(622, 187);
pick5Loc = Location(794, 187);
pick6Loc = Location(966, 187);
pick7Loc = Location(1138, 187);
pickAllLoc = {pick1Loc, pick2Loc, pick3Loc, pick4Loc, pick5Loc, pick6Loc, pick7Loc};
rarityAllLoc = Location(317, 577);
rarityCommonLoc = Location(476, 582);
rarityConfirmLoc = Location(761, 669);
retireConfirmLoc1 = Location(1110, 678);
retireConfirmLoc2 = Location(1005, 631);
levelLoc = Location(1167, 39);
retireDisassembleLoc = Location(758, 489);
SelectFleetClear2 = Location(1130, 345);
SelectFleetClear3 = Location(1126, 502);
SelectFleetChoose1 = Location(1043, 209);
SelectFleetChoose2 = Location(1042, 347);
SelectFleetChoose3 = Location(1042, 501);
aviationLoc = Location(822, 610);
torpedoLoc = Location(997, 609);
artilleryLoc = Location(1222, 611);
center = getGameArea():getCenter();
moveLoc = Location(149, 589);
safeClickLoc = Location(515, 24);
sosMissionLoc = Location(1193, 523);
searchSignalLcc = Location(930, 576);