---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Olegase.
--- DateTime: 26.04.2019 21:33
---
-- TODO: Поиск босса по крестовой
-- TODO: Управляемое количество боев для каждого флота
-- TODO: Менять флот, когда упадет мораль

-- Settings
Settings:setCompareDimension(true, 1280);
Settings:setScriptDimension(true, 1280);
package.path = package.path..";"..scriptPath().."?.lua";
isAngle = false;
onlyBossIsLeft = false;
fleetChanged = false;
shipsMoraleChecked = false;
mapSelected = false;
unableToReachTargetLocationCheck = false;
attemptsToFightBoss = 1;
standardTimeInterval = 0.5;
acceleratedTimeInterval = 0.1;
countOfDefeatedFoes = 0;
runCount = 0;
standardSwipeCheck = true;

-- Functions
require("BattleChecks");
require("BattleHandlers");
require("Battle");
require("Port");
require("Other");
require("Daily");
require("SosMission");

-- Regions
require("Regions");

-- Colors
require("Colors");

-- Objects
require("ObjectsBattle");
require("ObjectsPort");
require("ObjectsDaily");

-- Locations
require("Locations");

-- Main program

debugStatus("Start program");
settingsBot();
dailyMission();
sosMission();
battleMission();

print("Well done!");