---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Olegase.
--- DateTime: 05.05.2019 21:28
---

-- Объекты для ежедневные

emptyDaily = Pattern("EmptyDaily.png"):similar(0.9);
escortCargo = Pattern("EscortCargo.png"):similar(0.9);
maritimeAttack = Pattern("MaritimeAttack.png"):similar(0.9);
tacticalTraining = Pattern("TacticalTraining.png"):similar(0.9);
urgentOps = Pattern("UrgentOps.png"):similar(0.9);
groupsMode = {tacticalTraining, maritimeAttack, escortCargo, urgentOps};
fleet1 = Pattern("Fleet1.png"):similar(0.99);
fleet2 = Pattern("Fleet2.png"):similar(0.99);
fleet3 = Pattern("Fleet3.png"):similar(0.99);
fleet4 = Pattern("Fleet4.png"):similar(0.99);
fleetAll = {fleet1, fleet2, fleet3, fleet4};
outOfDailyChallenge = Pattern("OutOfDailyChallenge.png"):similar(0.9);