---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Olegase.
--- DateTime: 05.05.2019 21:28
---

-- Объекты для порта

dock1 = Pattern("Dock.png"):similar(0.9);
dock2 = Pattern("Dock2.png"):similar(0.9);
back = Pattern("Back.png"):similar(0.9);
backDorm = Pattern("BackDorm.png"):similar(0.9);
normal = Pattern("Normal.png"):similar(0.9);
attack1 = Pattern("Attack.png"):similar(0.9);
attack2 = Pattern("Attack2.png"):similar(0.9);
daily1 = Pattern("Daily1.png"):similar(0.9);
daily2 = Pattern("Daily2.png"):similar(0.9);
available = Pattern("Available.png"):similar(0.9);
descending = Pattern("Descending.png"):similar(0.9);
commonButton = Pattern("CommonButton.png"):similar(0.9);
levelButton = Pattern("LevelButton.png"):similar(0.9);
firstFleet = Pattern("FirstFleet.png"):similar(0.9);
firstFleetSelected = Pattern("FirstFleetSelected.png"):similar(0.9);
secondFleet = Pattern("SecondFleet.png"):similar(0.9);
secondFleetSelected = Pattern("SecondFleetSelected.png"):similar(0.9);
thirdFleet = Pattern("ThirdFleet.png"):similar(0.9);
thirdFleetSelected = Pattern("ThirdFleetSelected.png"):similar(0.9);
fourthFleet = Pattern("FourthFleet.png"):similar(0.9);
fourthFleetSelected = Pattern("FourthFleetSelected.png"):similar(0.9);
selectFleetAll = {firstFleet, secondFleet, thirdFleet, fourthFleet};
selectFleetAllSelected = {firstFleetSelected, secondFleetSelected, thirdFleetSelected, fourthFleetSelected};
number0 = Pattern("0.png"):similar(0.9);
number2 = Pattern("2.png"):similar(0.9);
go3 = Pattern("Go3.png"):similar(0.9);
green = Pattern("Green.png"):similar(0.9);