---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Olegase.
--- DateTime: 29.04.2019 17:35
---

-- Области

missionReg = nil;
inProgressReg2 = nil;
battleArea = Region(120, 55, 1160, 665);
standardArea = getGameArea();
battleButtonReg = Region(900, 570, 320, 140);
statusReg = Region(320, 5, 200, 25);
evadeReg = Region(780, 330, 250, 100);
ambushReg = Region(450, 270, 400, 50);
offReg = Region(120, 60, 120, 60);
cancelReg = Region(530, 480, 220, 90);
tapToContinueReg = Region(500, 540, 280, 60);
confirmReg1 = Region(1000, 560, 220, 100);
confirmReg2 = Region(530, 450, 220, 90);
confirmReg3 = Region(674, 452, 229, 89);
confirmReg4 = Region(649, 627, 218, 84);
switchReg = Region(830, 630, 220, 80);
goButtonReg1 = Region(820, 430, 220, 100);
goButtonReg2 = Region(960, 580, 220, 90);
messageBoxReg = Region(150, 300, 1000, 70);
dockIsFullReg = Region(410, 310, 460, 70);
currentShipReg = nil;
backReg = Region(0, 0, 90, 60);
backDormReg = Region(0, 0, 90, 60);
dockReg = Region(130, 650, 180, 70);
attackReg = Region(965, 345, 260, 110);
missionModeReg = Region(80, 0, 150, 50);
dailyReg1 = Region(673, 619, 196, 90);
dailyModeReg = Region(539, 67, 239, 569);
dailyAttemptsReg = Region(5, 583, 208, 128);
dailyFleetReg = Region(5, 118, 124, 71);
runCounterReg = Region(530, 5, 50, 25);
attemptsReg = Region(320, 35, 80, 25);
selectFleetReg = Region(961, 157, 232, 518);
pauseButtonReg = Region(1117, 17, 153, 72);
normalReg = Region(0, 609, 215, 114);
shipIconReg = Region(0, 66, 118, 652);
commandMenuReg = Region(579, 628, 689, 79);
starsReg = Region(1235, 97, 45, 105);
forbiddenRegs = {starsReg};
sosMissionReg = Region(1153, 495, 75, 65);
sosSignalGoReg = Region(822, 226, 168, 59);
exitButtonReg = Region(871, 152, 115, 81);
autoBattleOffReg = Region(22, 19, 72, 67);
levelButtonReg = Region(1078, 2, 179, 63);
commonButtonReg = Region(397, 548, 159, 67);